# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransaction',
            name='body',
            field=models.CharField(default='NONE', max_length=3500),
        ),
        migrations.AlterField(
            model_name='webhooktransaction',
            name='request_meta',
            field=models.CharField(default='NONE', max_length=3500),
        ),
    ]
